FROM wasr21containerregistry.azurecr.io/base_platform_install:0.6.3

COPY files /install/ansible/bp
COPY bp_config_vars.yml /install/ansible/bp_config_vars.yml
COPY tanzu_config_vars.yml /install/ansible/tanzu_config_vars.yml
