{
 "title": "KAFKA DASHBOARD",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Topics",
    "query": "label_values(kafka_log_log_value,topic)"
   },
   {
    "name": "Error",
    "query": "label_values(kafka_network_requestmetrics_count,error)"
   },
   {
    "name": "Request",
    "query": "label_values(kafka_network_requestmetrics_count,request)"
   },
   {
    "name": "Broker",
    "query": "label_values(kafka_network_socketserver_value,instance)"
   },
   {
    "name": "Zookeeper_SessionState",
    "query": "label_values(kafka_server_sessionexpirelistener_count,name)"
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "KUBERNETES_NAME",
    "query": "label_values(kafka_network_requestmetrics_max,kubernetes_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Messages In Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_count{name=\"MessagesInPerSec\",topic!=\"\",topic=~\"$Topics\",}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "UnderReplicatedPartitions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=\"UnderReplicatedPartitions\",kubernetes_name=~\"$KUBERNETES_NAME\"} )",
     "legendFormat": "{{Kubernetes_name}} {{$KUBERNETES_NAME}}"
    }
   ]
  },
  {
   "title": "Messages Out Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Bytes In Per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_count{name=\"BytesInPerSec\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "Bytes Out Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_count{name=\"BytesOutPerSec\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "ReplicationBytesInPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_count{name=\"ReplicationBytesInPerSec\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "ReplicationBytesOutPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_count{name=\"ReplicationBytesOutPerSec\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "ErrorsPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_count{name=\"ErrorsPerSec\",request=\"$Request\",error=\"$Error\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m]))",
     "legendFormat": "[{{kubernetes_name}} {{instance}}][{{Error}}: $Error]"
    }
   ]
  },
  {
   "title": "RequestPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_count{name=\"RequestsPerSec\",request=\"Produce\",}[5m]))",
     "legendFormat": "[{{Kafka_Broker_Instance}}:$Broker] [{{request=Produce}}]"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_count{name=\"RequestsPerSec\",request=\"FetchConsumer\"}[5m]))",
     "legendFormat": "[{{Kafka_Broker_Instance}}:$Broker] [{{request=FetchConsumer}}]"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_count{name=\"RequestsPerSec\",request=\"FetchFollower\"}[5m]))",
     "legendFormat": "[{{Kafka_Broker_Instance}}:$Broker] [{{request=FetchFollower}}]"
    },
    {
     "expr": "sum(rate(kafka_network_requestmetrics_count{name=\"RequestsPerSec\",request=\"Fetch\"}[5m]))",
     "legendFormat": "[{{Kafka_Broker_Instance}}:$Broker] [{{request=Fetch}}]"
    }
   ]
  },
  {
   "title": "TemporaryMemoryBytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"TemporaryMemoryBytes\",request=\"Fetch\",kubernetes_name=\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}][{{Request:Fetch}}]"
    },
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"TemporaryMemoryBytes\",request=\"Produce\",kubernetes_name=\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}][{{Request:Produce}}]"
    }
   ]
  },
  {
   "title": "MessageConversionsTimeMs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"MessageConversionsTimeMs\",request=\"Fetch\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": " [{{kubernetes_name}} {{instance}}] [{{request=Fetch}}] "
    },
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"MessageConversionsTimeMs\",request=\"Produce\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}][{{request=Produce}}]"
    }
   ]
  },
  {
   "title": "RequestBytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_count{name=\"RequestBytes\",request=\"$Request\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m]))",
     "legendFormat": "[{{kubernetes_name}} {{instance}}][{{Request}}:{{$Request}}]"
    }
   ]
  },
  {
   "title": "MessageConversionsPerSec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_count{name=\"FetchMessageConversionsPerSec\",topic!=\"\",topic=~\"$Topics\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}][{{name=FetchMessageConversionsPerSec}}] [{{Topic}}:{{$Topics}}]"
    },
    {
     "expr": "rate(kafka_server_brokertopicmetrics_count{name=\"ProduceMessageConversionsPerSec\",topic!=\"\",topic=~\"$Topics\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{name=ProduceMessageConversionsPerSec}}]  [{{Topic}}:{{$Topics}}]"
    }
   ]
  },
  {
   "title": "Log flush rate and time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_log_logflushstats_logflushrateandtimems_count{kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "OfflineLogDirectoryCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_log_logmanager_value{name=\"OfflineLogDirectoryCount\",kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "ActiveControllerCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_controller_kafkacontroller_value{name=\"ActiveControllerCount\",kubernetes_name=\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "PartitionCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 136 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_replicamanager_value{name=\"PartitionCount\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "UncleanLeaderElectionsPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_controller_controllerstats_count{name=\"UncleanLeaderElectionsPerSec\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{count}}] "
    },
    {
     "expr": "rate(kafka_controller_controllerstats_meanrate{name=\"UncleanLeaderElectionsPerSec\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Meanrate}}] "
    },
    {
     "expr": "rate(kafka_controller_controllerstats_fifteenminuterate{name=\"UncleanLeaderElectionsPerSec\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{FiftenMinuterate}}] "
    }
   ]
  },
  {
   "title": "IsrExpandsPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_replicamanager_count{name=\"IsrExpandsPerSec\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "IsrShrinksPerSec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_replicamanager_count{name=\"IsrShrinksPerSec\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "Requests waiting in the producer purgatory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 168 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_delayedoperationpurgatory_value{name=\"PurgatorySize\",delayedOperation=\"Produce\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "Requests waiting in the Fetch purgatory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 176 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_delayedoperationpurgatory_value{name=\"PurgatorySize\",delayedOperation=\"Fetch\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "UnderMinIsrPartitionCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 185 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_value{name=\"UnderMinIsrPartitionCount\",kubernetes_name=~\"$KUBERNETES_NAME\"} ",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "LeaderElectionRateAndTimeMs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 193 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_count{name=\"LeaderElectionRateAndTimeMs\",} )",
     "legendFormat": "[{{Kafka_Broker_Instance}}:$Broker] [{{count}}] "
    },
    {
     "expr": "sum(kafka_controller_controllerstats_min{name=\"LeaderElectionRateAndTimeMs\",} )",
     "legendFormat": "[{{Kafka_Broker_Instance}}:$Broker] [{{min}}] "
    },
    {
     "expr": "sum(kafka_controller_controllerstats_fiveminuterate{name=\"LeaderElectionRateAndTimeMs\",} )",
     "legendFormat": "[{{Kafka_Broker_Instance}}:$Broker] [{{FiveMinuterate}}] "
    },
    {
     "expr": "sum(kafka_controller_controllerstats_fifteenminuterate{name=\"LeaderElectionRateAndTimeMs\",} )",
     "legendFormat": "[{{Kafka_Broker_Instance}}:$Broker] [{{FifteenMinuterate}}] "
    },
    {
     "expr": "sum(kafka_controller_controllerstats_75thpercentile{name=\"LeaderElectionRateAndTimeMs\",} )",
     "legendFormat": "[{{Kafka_Broker_Instance}}:$Broker] [{{75thPercentile}}] "
    },
    {
     "expr": "sum(kafka_controller_controllerstats_99thpercentile{name=\"LeaderElectionRateAndTimeMs\",} )",
     "legendFormat": "[{{Kafka_Broker_Instance}}:$Broker] [{{99thPercentile}}] "
    }
   ]
  },
  {
   "title": "LeaderCount",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_value{name=\"LeaderCount\",kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "MaxLag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 211 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_replicafetchermanager_value{name=\"MaxLag\",clientId=\"Replica\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "{{kubernetes_name}} {{instance}}"
    }
   ]
  },
  {
   "title": "ConsumerLag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 219 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_fetcherlagmetrics_value{name=\"ConsumerLag\",clientId!=\"\",topic!=\"\",topic=~\"$Topics\",partition!=\"\"}[5m]))",
     "legendFormat": " [{{Topic}}:$Topics]"
    }
   ]
  },
  {
   "title": "Reuest Total Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 227 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"TotalTimeMs\",request=\"Produce\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Request:Produce}}] "
    },
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"TotalTimeMs\",request=\"FetchConsumer\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]  [{{Request:FetchConsumer}}] "
    },
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"TotalTimeMs\",request=\"FetchFollower\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Request:FetchFollower}}] "
    }
   ]
  },
  {
   "title": "Time the request waits in the request queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 236 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"RequestQueueTimeMs\",request=\"Produce\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Request:Produce}}] "
    },
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"RequestQueueTimeMs\",request=\"FetchFollower\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Request:FetchFollower}}] "
    },
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"RequestQueueTimeMs\",request=\"FetchConsumer\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Request:FetchConsumer}}] "
    }
   ]
  },
  {
   "title": "Time the request is processed at the leader",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 245 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"LocalTimeMs\",request=\"Produce\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}][{{Request:Produce}}] "
    },
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"LocalTimeMs\",request=\"FetchConsumer\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Request:FetchConsumer}}] "
    },
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"LocalTimeMs\",request=\"FetchFollower\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Request:FetchFollower}}] "
    }
   ]
  },
  {
   "title": "Time the request waits for the follower",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 253 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"RemoteTimeMs\",request=\"Produce\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Request:Produce}}] "
    },
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"RemoteTimeMs\",request=\"FetchConsumer\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Request:FetchConsumer}}] "
    },
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"RemoteTimeMs\",request=\"FetchFollower\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Request:FetchFollower}}] "
    }
   ]
  },
  {
   "title": "Time the request waits in the response queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 261 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_min{name=\"ResponseQueueTimeMs\",request=\"Produce\",}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Request:Produce}}] "
    },
    {
     "expr": "rate(kafka_network_requestmetrics_min{name=\"ResponseQueueTimeMs\",request=\"FetchConsumer\",}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Request:FetchConsumer}}] "
    },
    {
     "expr": "rate(kafka_network_requestmetrics_min{name=\"ResponseQueueTimeMs\",request=\"FetchFollower\",}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}][{{Request:FetchFollower}}] "
    }
   ]
  },
  {
   "title": "ConsumerFetchManager",
   "type": "graph",
   "description": "Number of messages the consumer lags behind the producer by. Published by the consumer, not broker.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 268 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_consumerfetchermanager_value{name=\"MaxLag\",clientId!=\"\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "Time to send the response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 276 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"ResponseSendTimeMs\",request=\"Produce\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Request}}:{{Produce}}] "
    },
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"ResponseSendTimeMs\",request=\"FetchConsumer\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Request:FetchConsumer}}] "
    },
    {
     "expr": "rate(kafka_network_requestmetrics_count{name=\"ResponseSendTimeMs\",request=\"FetchFollower\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Request:FetchFollower}}] "
    }
   ]
  },
  {
   "title": "NetworkProcessorAvgIdlePercent",
   "type": "graph",
   "description": "The average fraction of time the network processors are idle",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 284 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_socketserver_value{name=\"NetworkProcessorAvgIdlePercent\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "The average fraction of time the request handler threads are idle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 292 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_kafkarequesthandlerpool_count{name=\"RequestHandlerAvgIdlePercent\",}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "ZooKeeper client request latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 301 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_zookeeperclientmetrics_count{name=\"ZooKeeperRequestLatencyMs\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "ZOOKEEPER_SessionState",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 309 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_sessionexpirelistener_count{name=\"$Zookeeper_SessionState\",kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] "
    }
   ]
  },
  {
   "title": "OfflinePartitionsCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 317 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_controller_kafkacontroller_value{name=\"OfflinePartitionsCount\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[{{kubernetes_name}} {{instance}}]"
    }
   ]
  },
  {
   "title": "Produce request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 324 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_count{name=\"TotalProduceRequestsPerSec\",topic!=\"\",topic=~\"$Topics\",}",
     "legendFormat": "[{{kubernetes_name}} {{instance}}] [{{Topic}}:{{topic}}]"
    }
   ]
  },
  {
   "title": "Fetch request rate.",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 332 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_count{name=\"TotalFetchRequestsPerSec\",topic!=\"\",topic=~\"$Topics\"})",
     "legendFormat": "[{{Topic}}:$Topics]"
    }
   ]
  },
  {
   "title": "Produce request rate for requests that failed.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 341 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_count{name=\"FailedProduceRequestsPerSec\",topic!=\"\",topic=~\"$Topics\"}",
     "legendFormat": "[ {{kubernetes_name}} {{instance}}]  [{{Processor}}:{{processor}}] [{{Topic}}:$Topics]"
    }
   ]
  },
  {
   "title": "Fetch request rate for requests that failed.",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 349 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_count{name=\"FailedFetchRequestsPerSec\",kubernetes_name=~\"$KUBERNETES_NAME\"}",
     "legendFormat": "[ {{kubernetes_name}} {{instance}}]  "
    }
   ]
  },
  {
   "title": "RequestQueueSize",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 356 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_network_requestchannel_value{name=\"ResponseQueueSize\",processor!=\"\",kubernetes_name=~\"$KUBERNETES_NAME\"}[5m])",
     "legendFormat": "[ {{kubernetes_name}} {{instance}}]  [{{Processor}}:{{processor}}] "
    }
   ]
  }
 ]
}