{
 "title": "MariaDB MaxScale",
 "tags": [
  "mariadb",
  "maxscale"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(maxscale_server_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "MaxScale Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "maxscale_status_uptime{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Average Event Queue Length",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "maxscale_status_avg_event_queue_length{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "maxscale_status_connections{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Apdex Score",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(maxscale_events_queued_seconds_bucket{le=\"0.1\", instance=\"$host\"}[$interval])) by (job) + sum(rate(maxscale_events_queued_seconds_bucket{le=\"0.5\", instance=\"$host\"}[$interval])) by (job) ) / 2 /  sum(rate(maxscale_events_queued_seconds_count{instance=\"$host\"}[$interval])) by (job)",
     "legendFormat": "Apdex Score"
    }
   ]
  },
  {
   "title": "Apdex",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "content": "This Apdex panel is calibrated for a 100ms as the target request duration and the upper bound of the tolerated request duration of 500ms. "
  },
  {
   "title": "Event Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ops", "label": "ops/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(maxscale_events_queued_seconds_bucket{instance=\"$host\"}[$interval]))",
     "legendFormat": "Queued"
    },
    {
     "expr": "sum(rate(maxscale_events_executed_seconds_bucket{instance=\"$host\"}[$interval]))",
     "legendFormat": "Executed"
    }
   ]
  },
  {
   "title": "Event Queue Length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Events" }
   ],
   "targets": [
    {
     "expr": "maxscale_status_max_event_queue_length{instance=\"$host\"}",
     "legendFormat": "pending"
    }
   ]
  },
  {
   "title": "Read / Write Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops", "label": "Operations / Sec" }
   ],
   "targets": [
    {
     "expr": "irate(maxscale_status_read_events{instance=\"$host\"}[$interval])",
     "legendFormat": "reads / sec"
    },
    {
     "expr": "irate(maxscale_status_write_events{instance=\"$host\"}[$interval])",
     "legendFormat": "writes / sec"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "maxscale_status_backend_connections{instance=\"$host\"}",
     "legendFormat": "Backend"
    },
    {
     "expr": "maxscale_status_client_connections{instance=\"$host\"}",
     "legendFormat": "Client"
    }
   ]
  },
  {
   "title": "Max Time in Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(maxscale_events_queued_seconds_sum{instance=\"$host\"}[$interval]) / rate(maxscale_events_queued_seconds_count{instance=\"$host\"}[$interval])",
     "legendFormat": "max flight time"
    }
   ]
  },
  {
   "title": "Server Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "maxscale_server_connections{instance=\"$host\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Service Sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "Sessions" }
   ],
   "targets": [
    {
     "expr": "maxscale_service_current_sessions{instance=\"$host\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}