{
 "title": "SCHEMA_REGISTRY_DASHBOARD",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "INSTANCE",
    "query": "label_values(kafka_schema_registry_jersey_metrics_compatibility_subjects_versions_verify_request_error_rate,instance)"
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "RELEASE_NAME",
    "query": "label_values(kafka_schema_registry_jersey_metrics_compatibility_subjects_versions_verify_request_rate,kubernetes_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "MASTER_SLAVE_ROLE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_master_slave_role_master_slave_role{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "OPENED_CONNECTION_RATE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jetty_metrics_connections_opened_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "CLOSED_CONNECTION_RATE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jetty_metrics_connections_closed_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "CONNECTIONS_ACTIVE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jetty_metrics_connections_active{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "CONNECTION_ACCEPTED_RATE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jetty_metrics_connections_accepted_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_REGISTER_RESPONSE(RESPONSE_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_register_response_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_REGISTER_RESPONSE(RESPONSE_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_register_response_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_REGISTER_RESPONSE (RESPONSE_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_register_response_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_REGISTER_RESPONSE(RESPONSE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_register_response_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_REGISTER_REQUEST(REQUEST_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_register_request_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_REGISTER_REQUEST(REQUEST_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_register_request_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_REGISTER_REQUEST(REQUEST_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_register_request_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_REGISTER_REQUEST(REQUEST_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_register_request_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_REGISTER_REQUEST (REQUEST_LATENCY_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_register_request_latency_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_REGISTER_REQUEST(REQUEST_LATENCY_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_register_request_latency_max {kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_REGISTER_REQUEST(REQUEST_ERROR_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_register_request_error_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_RESPONSE(RESPONSE_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_response_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_RESPONSE(RESPONSE_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_response_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_RESPONSE(RESPONSE_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_response_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_RESPONSE(RESPONSE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_response_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_REQUEST(REQUEST_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_request_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_REQUEST(REQUEST_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_request_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_REQUEST(REQUEST_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_request_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_REQUEST(REQUEST_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_request_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_REQUEST(REQUEST_LATENCY_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_request_latency_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_REQUEST(REQUEST_LATENCY_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_request_latency_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_REQUEST(REQUEST_ERROR_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 139 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_request_error_rate{kubernetes_name=~\"$RELEASE_NAME\",} ",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_ONLY_RESPONSE(RESPONSE_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_only_response_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_ONLY_RESPONSE(RESPONSE_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 148 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_only_response_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_ONLY_RESPONSE(RESPONSE_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 157 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_only_response_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_ONLY_RESPONSE(RESPONSE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 157 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_only_response_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_ONLY_REQUEST(REQUEST_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_only_request_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_ONLY_REQUEST(REQUEST_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 166 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_only_request_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_ONLY_REQUEST(REQUEST_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 175 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_only_request_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_ONLY_REQUEST(REQUEST_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 175 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_only_request_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_ONLY_REQUEST(REQUEST_LATENCY_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 184 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_only_request_latency_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_ONLY_REQUEST(REQUEST_LATENCY_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 184 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_only_request_latency_max{kubernetes_name=~\"$RELEASE_NAME\",} ",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "VERSION_GET_SCHEMA_ONLY_REQUEST(REQUEST_ERROR_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 193 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_get_schema_only_request_error_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "DELETESCHEMA_VERSION_SCHEMA_RESPONSE(RESPONSE_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_deleteschemaversion_schema_response_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "DELETESCHEMA_VERSION_SCHEMA_RESPONSE(RESPONSE_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 202 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_deleteschemaversion_schema_response_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "DELETESCHEMA_VERSION_SCHEMA_RESPONSE(RESPONSE_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 211 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_deleteschemaversion_schema_response_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "DELETESCHEMA_VERSION_SCHEMA_RESPONSE(RESPONSE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 211 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_deleteschemaversion_schema_response_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "DELETESCHEMA_VERSION_SCHEMA_REQUEST(REQUEST_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 220 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_deleteschemaversion_schema_request_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "DELETESCHEMA_VERSION_SCHEMA_REQUEST(REQUEST_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 220 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_deleteschemaversion_schema_request_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "DELETESCHEMA_VERSION_SCHEMA_REQUEST(REQUEST_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 229 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_deleteschemaversion_schema_request_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "DELETESCHEMA_VERSION_SCHEMA_REQUEST (REQUEST_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 229 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_deleteschemaversion_schema_request_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "DELETESCHEMA_VERSION_SCHEMA_REQUEST  (REQUEST_LATENCY_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 238 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_deleteschemaversion_schema_request_latency_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "DELETESCHEMA_VERSION_SCHEMA_REQUEST  (REQUEST_LATENCY_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 238 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_deleteschemaversion_schema_request_latency_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "DELETESCHEMA_VERSION_SCHEMA_REQUEST (REQUEST_ERROR_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 247 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_versions_deleteschemaversion_schema_request_error_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_LIST(REQUEST_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 256 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_list_request_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_LIST(REQUEST_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 256 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_list_request_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_LIST(REQUEST_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 265 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_list_request_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_LIST(REQUEST_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 265 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_list_request_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_LIST(REQUEST_LATENCY_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 274 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_list_request_latency_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_LIST(REQUEST_LATENCY_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 274 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_list_request_latency_max{kubernetes_name=~\"$RELEASE_NAME\",} ",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_LIST(REQUEST_ERROR_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 283 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_list_request_error_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_LIST(RESPONSE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 283 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_list_response_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_LIST(RESPONSE_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 292 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_list_response_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_LIST(RESPONSE_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 292 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_list_response_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_LIST(RESPONSE_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 301 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_list_response_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_GET(REQUEST_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 310 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_get_schema_request_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_GET(REQUEST_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 310 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_get_schema_request_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_GET(REQUEST_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 319 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_get_schema_request_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_GET(REQUEST_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 319 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_get_schema_request_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_GET(REQUEST_LATENCY_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 328 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_get_schema_request_latency_avg{kubernetes_name=~\"$RELEASE_NAME\",} ",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_GET(REQUEST_LATENCY_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 328 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_get_schema_request_latency_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_GET(REQUEST_ERROR_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 337 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_get_schema_request_error_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_GET_RESPONSE (RESPONSE_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 346 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_get_schema_response_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_GET_RESPONSE (RESPONSE_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 346 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_get_schema_response_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_GET_RESPONSE(RESPONSE_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 355 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_get_schema_response_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SUBJECTS_GET_RESPONSE (RESPONSE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 355 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_get_schema_response_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_DELETE_SUBJECT(RESPONSE_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 364 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_delete_subject_response_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_DELETE_SUBJECT(RESPONSE_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 364 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_delete_subject_response_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_DELETE_SUBJECT(RESPONSE_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 373 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_delete_subject_response_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_DELETE_SUBJECT(RESPONSE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 373 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_delete_subject_response_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_DELETE_SUBJECT(REQUEST_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 382 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_delete_subject_request_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_DELETE_SUBJECT(REQUEST_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 382 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_delete_subject_request_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_DELETE_SUBJECT (REQUEST_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 391 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_delete_subject_request_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_DELETE_SUBJECT (REQUEST_ERROR_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 391 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_delete_subject_request_error_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_DELETE_SUBJECT(REQUEST_LATENCY_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 400 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_delete_subject_request_latency_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_DELETE_SUBJECT (REQUEST_LATENCY_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 400 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_delete_subject_request_latency_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_DELETE_SUBJECT (REQUEST)(REQUEST_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 409 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_delete_subject_request_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SCHEMA_ID (GET_SCHEMA)(RESPONSE_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 418 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_schemas_ids_get_schema_response_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SCHEMA_ID (GET_SCHEMA)(RESPONSE_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 418 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_schemas_ids_get_schema_response_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SCHEMA_ID (GET_SCHEMA)(RESPONSE_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 427 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_schemas_ids_get_schema_response_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SCHEMA_ID (GET_SCHEMA)(RESPONSE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 427 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_schemas_ids_get_schema_response_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SCHEMA_ID(GET_SCHEMA_REQUEST)(REQUEST_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 436 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_schemas_ids_get_schema_request_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SCHEMA_ID(REQUEST_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 436 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_schemas_ids_get_schema_request_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SCHEMA_ID (REQUEST_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 445 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_schemas_ids_get_schema_request_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SCHEMA_ID(REQUEST_ERROR_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 445 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_schemas_ids_get_schema_request_error_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SCHEMA_ID(REQUEST_LATENCY_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 454 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_schemas_ids_get_schema_request_latency_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SCHEMA_ID (GET_SCHEMA_REQUEST)(REQUEST_LATENCY_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 454 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_schemas_ids_get_schema_request_latency_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY_SCHEMA_ID (REQUEST_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 463 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_schemas_ids_get_schema_request_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY(REQUEST_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 472 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_request_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY (REQUEST_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 472 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_request_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY(REQUEST_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 481 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_request_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY(REQUEST_ERROR_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 481 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_request_error_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY(REQUEST_LATENCY_AVG",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 490 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_request_latency_avg{kubernetes_name=~\"$RELEASE_NAME\",} ",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY (REQUEST_LATENCY_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 490 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_request_latency_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_JERSEY(REQUEST_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 5, "y": 499 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_request_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_COMPATIBLE_VERSION_VERIFY (RESPONSE_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 508 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_compatibility_subjects_versions_verify_response_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_COMPATIBLE_VERSION_VERIFY (RESPONSE_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 508 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_compatibility_subjects_versions_verify_response_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_COMPATIBLE_VERSION_VERIFY(RESPONSE_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 517 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_compatibility_subjects_versions_verify_response_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_COMPATIBLE_VERSION_VERIFY (RESPONSE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 517 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_compatibility_subjects_versions_verify_response_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_COMPATIBLE_VERSION_VERIFY(REQUEST_BYTE_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 526 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_compatibility_subjects_versions_verify_request_byte_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_COMPATIBLE_VERSION_VERIFY(REQUEST_ERROR_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 526 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_compatibility_subjects_versions_verify_request_error_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_COMPATIBLE_VERSION_VERIFY (REQUEST_LATENCY_AVG)(REQUEST_LATENCY_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 535 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_compatibility_subjects_versions_verify_request_latency_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_COMPATIBLE_VERSION_VERIFY (REQUEST_LATENCY_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 535 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_compatibility_subjects_versions_verify_request_latency_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_COMPATIBLE_VERSION_VERIFY(REQUEST_RATE)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 544 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_compatibility_subjects_versions_verify_request_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_COMPATIBLE_VERSION_VERIFY(REQUEST_SIZE_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 544 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_compatibility_subjects_versions_verify_request_size_avg{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_SCHEMA_REGISTRY_COMPATIBLE_VERSION_VERIFY(REQUEST_SIZE_MAX)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 553 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_compatibility_subjects_versions_verify_request_size_max{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_CONSUMER_FETCH_MANAGER(RECORDS_LAG_MAX)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 562 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_rate{client_id!=\"\",kubernetes_name=~\"$RELEASE_NAME\"}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  },
  {
   "title": "KAFKA_CONSUMER_FETCH_MANAGER(RECORDS_LAG_AVG)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 570 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumer_consumer_node_metrics_outgoing_byte_rate{client_id!=\"\",node_id!=\"\",kubernetes_name=~\"$RELEASE_NAME\"}\r\n",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}] [{{Node_id:}}{{node_id}}]"
    }
   ]
  },
  {
   "title": "KAFKA_CONSUMER_FETCH_MANAGER(RECORDS_LAG)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 579 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_schema_registry_jersey_metrics_subjects_get_schema_request_rate{kubernetes_name=~\"$RELEASE_NAME\",}",
     "legendFormat": "[{{Schema_Registry_Instance }}:   {{ instance}}] [{{Kubernetes_Name:}}{{kubernetes_name}}]"
    }
   ]
  }
 ]
}