#!/bin/bash
function usage (){
    echo -e "USAGE: \n"
    echo -e  "\tfpm-password en \$your-plain-password \$AES-pass\n"
    echo -e  "\tfpm-password de \$your-encrypted-password \$AES-pass\n"
    exit 1
}

# Take example...
# -pass pass:zhiyuan-nokia
# -S    random generate by Openssl
# ------->
# -key  42D6AD81E5F13364257D7499E995CE3A49F37779B96A364DD52EABD2C5BC2A1E
# -iv   7D2919C81F7BB02ABCD89F95395B6842
which openssl >> /dev/null 2>&1  
if [[ $? != 0 ]]; then
    echo -e "ERROR, no OpenSSL..."
    exit 1;
fi

if [[ $# != 3 ]]; then
    usage
else
    cmd="echo %s | openssl enc %s -a -aes-256-cbc -pass pass:$3"
    case $1 in 
        "en")
            full_cmd=`printf "$cmd" "$2" "-e"`
            result=$(eval "$full_cmd")
            echo $result
        ;;
        "de")
            full_cmd=`printf "$cmd" "$2" "-d"`
            result=$(eval "$full_cmd")
            echo $result
        ;;
        *)
            usage
        ;;
    esac
fi

